### ISSUE TITLE
[Server] - Job to search for bookmarks that have no image

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#173]
- [ ] Enable Scheduling: 
  - https://www.baeldung.com/spring-scheduled-tasks
  - `@EnableScheduling` on the main class 

In BookmarkService.java
- [ ] Create a conjob that runs once a day. 
- [ ] Find all Bookmarks from the bookmark Repository have a screenshot and are scrapable.
  - Missing screenshotUrls are then attempted to be retrieved by calling the sManager. 
- [ ] Add method to BookmarkRepository to run the query for where url is `""` (i.e. empty)

**Comment by joelramilison** [comment]
I've seen that the BookmarkController takes in a 'scrapable' boolean when you create a new Bookmark (which is then checked for before the initial title + screenshot scrape). If we build this daily 'fetch missing screenshots' feature in BookmarkService, we won't be able to check this value again since it isn't saved. This could lead to a retrieval of screenshots for sites that initially weren't scrapable. What do you think?

**Comment by pisal-shubham** [comment]
Hello @R-Sandor, I'm interested in working on this issue. Could I work on it?
