### ISSUE TITLE
[Frontend] Add About Route as Public

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#249]
# Details
Currently in the security service on the frontend the findfirst.dev/about routes the user back to login. We should change that to be public.

**Comment by GiannisPep** [comment]
Hi, I'd like to work on this issue! I understand that the task involves changing the /about route so that it no longer redirects users to the login page and instead becomes publicly accessible. I will update the frontend security service or routing logic to ensure that authentication is not required for this specific page, while maintaining security for other protected routes. Let me know if there are any additional requirements or considerations before I proceed.

**Comment by R-Sandor** [comment]
@GiannisPep Absolutely, thank you!

**Comment by GiannisPep** [comment]
I tried to clone the repository, but I encountered an error related to an invalid path due to the file name: data/test_screenshots/https:__facebook.com.png. It seems that the file name contains characters that are not allowed on my system (Windows). Here's the error message I received:

invalid path 'data/test_screenshots/https:__facebook.com.png'
unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by R-Sandor** [comment]
@GiannisPep Let me workout an alternative url scheme because in windows `:` is a reserved path.

**Comment by GiannisPep** [comment]
Do you want it to say something specific or is that fine
![Screenshot 2024-10-18 202038](https://github.com/user-attachments/assets/886ae948-a360-480a-b69e-0f86b9260876)

**Comment by R-Sandor** [comment]
That's a good starting point! I will accept that :D :rocket:

**Comment by GiannisPep** [comment]
#259

**Comment by GiannisPep** [comment]
#259

**Comment by R-Sandor** [comment]
Thank you @GiannisPep.
